##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## This is my makefile for my library
##


RED=\033[0;31m
GREEN=\033[0;32m
YELLOW=\033[1;33m
BLUE=\033[1;34m
WHITE=\033[1;37m
NC=\033[0m

SRC_DIR_LIB =	src/
OBJ_DIR_LIB =	obj/

SRC_LIBRARY	=	$(SRC_DIR_LIB)/my_check_string_is_number.c					\
				$(SRC_DIR_LIB)/my_compute_power_rec.c						\
				$(SRC_DIR_LIB)/my_compute_square_root.c						\
				$(SRC_DIR_LIB)/my_concat_params.c							\
				$(SRC_DIR_LIB)/my_cut_string.c								\
				$(SRC_DIR_LIB)/my_get_index_char.c							\
				$(SRC_DIR_LIB)/my_getnbr.c									\
				$(SRC_DIR_LIB)/my_get_nbr_operators.c						\
				$(SRC_DIR_LIB)/my_get_sign.c								\
				$(SRC_DIR_LIB)/my_intlen.c									\
				$(SRC_DIR_LIB)/my_int_to_str.c								\
				$(SRC_DIR_LIB)/my_perror.c									\
				$(SRC_DIR_LIB)/my_putchar.c									\
				$(SRC_DIR_LIB)/my_put_nbr.c									\
				$(SRC_DIR_LIB)/my_putstr.c									\
				$(SRC_DIR_LIB)/my_revstr.c									\
				$(SRC_DIR_LIB)/my_showstr.c									\
				$(SRC_DIR_LIB)/my_show_word_array.c							\
				$(SRC_DIR_LIB)/my_sort_int_array.c							\
				$(SRC_DIR_LIB)/my_strcapitalize.c							\
				$(SRC_DIR_LIB)/my_strcat.c									\
				$(SRC_DIR_LIB)/my_strcmp.c									\
				$(SRC_DIR_LIB)/my_strcpy.c									\
				$(SRC_DIR_LIB)/my_strdup.c									\
				$(SRC_DIR_LIB)/my_str_isalpha.c								\
				$(SRC_DIR_LIB)/my_str_islower.c								\
				$(SRC_DIR_LIB)/my_str_isnum.c								\
				$(SRC_DIR_LIB)/my_str_isprintable.c							\
				$(SRC_DIR_LIB)/my_str_isupper.c								\
				$(SRC_DIR_LIB)/my_strlen.c									\
				$(SRC_DIR_LIB)/my_strncat.c									\
				$(SRC_DIR_LIB)/my_strncmp.c									\
				$(SRC_DIR_LIB)/my_strncpy.c									\
				$(SRC_DIR_LIB)/my_strstr.c									\
				$(SRC_DIR_LIB)/my_str_to_int.c								\
				$(SRC_DIR_LIB)/my_str_to_word_array.c						\
				$(SRC_DIR_LIB)/my_strupcase.c								\
				$(SRC_DIR_LIB)/my_swap.c									\
				$(SRC_DIR_LIB)/my_putfloat.c								\
				$(SRC_DIR_LIB)/my_putlong.c									\
				$(SRC_DIR_LIB)/my_get_index_char.c							\
				$(SRC_DIR_LIB)/my_count_char.c								\
				$(SRC_DIR_LIB)/my_buffer.c									\
				$(SRC_DIR_LIB)/remove_spaces.c								\
				$(SRC_DIR_LIB)/my_binary_to_int.c							\
				$(SRC_DIR_LIB)/concat_slash.c								\
				$(SRC_DIR_LIB)/mem_set.c									\
				$(SRC_DIR_LIB)/my_glue_cut_str.c							\
				$(SRC_DIR_LIB)/gnl.c										\
				$(SRC_DIR_LIB)/my_str_alpha_or_int.c						\
				$(SRC_DIR_LIB)/my_char_is_alpha.c							\
				$(SRC_DIR_LIB)/my_char_is_int.c								\
				$(SRC_DIR_LIB)/my_print_address.c							\
				$(SRC_DIR_LIB)/my_printf.c									\
				$(SRC_DIR_LIB)/printfutils.c								\
				$(SRC_DIR_LIB)/printfutils_two.c							\
				$(SRC_DIR_LIB)/my_print_octal.c								\
				$(SRC_DIR_LIB)/printf/my_put_nbr_base.c						\
				$(SRC_DIR_LIB)/add_zeros_to_char.c							\
				$(SRC_DIR_LIB)/my_put_unsigned_int.c						\
				$(SRC_DIR_LIB)/my_int_to_binary.c							\
				$(SRC_DIR_LIB)/my_float_to_str.c							\
				$(SRC_DIR_LIB)/concat.c										\
				$(SRC_DIR_LIB)/my_str_to_float.c							\
				$(SRC_DIR_LIB)/concat_with_char.c							\
				$(SRC_DIR_LIB)/my_str_trim.c								\
				$(SRC_DIR_LIB)/my_str_starts_with.c							\
				$(SRC_DIR_LIB)/my_int_to_hexa.c


OBJ_LIBRARY =	$(OBJ_DIR_LIB)/my_check_string_is_number.o					\
				$(OBJ_DIR_LIB)/my_compute_power_rec.o						\
				$(OBJ_DIR_LIB)/my_compute_square_root.o						\
				$(OBJ_DIR_LIB)/my_concat_params.o							\
				$(OBJ_DIR_LIB)/my_cut_string.o								\
				$(OBJ_DIR_LIB)/my_get_index_char.o							\
				$(OBJ_DIR_LIB)/my_getnbr.o									\
				$(OBJ_DIR_LIB)/my_get_nbr_operators.o						\
				$(OBJ_DIR_LIB)/my_get_sign.o								\
				$(OBJ_DIR_LIB)/my_intlen.o									\
				$(OBJ_DIR_LIB)/my_int_to_str.o								\
				$(OBJ_DIR_LIB)/my_perror.o									\
				$(OBJ_DIR_LIB)/my_putchar.o									\
				$(OBJ_DIR_LIB)/my_put_nbr.o									\
				$(OBJ_DIR_LIB)/my_putstr.o									\
				$(OBJ_DIR_LIB)/my_revstr.o									\
				$(OBJ_DIR_LIB)/my_showstr.o									\
				$(OBJ_DIR_LIB)/my_show_word_array.o							\
				$(OBJ_DIR_LIB)/my_sort_int_array.o							\
				$(OBJ_DIR_LIB)/my_strcapitalize.o							\
				$(OBJ_DIR_LIB)/my_strcat.o									\
				$(OBJ_DIR_LIB)/my_strcmp.o									\
				$(OBJ_DIR_LIB)/my_strcpy.o									\
				$(OBJ_DIR_LIB)/my_strdup.o									\
				$(OBJ_DIR_LIB)/my_str_isalpha.o								\
				$(OBJ_DIR_LIB)/my_str_islower.o								\
				$(OBJ_DIR_LIB)/my_str_isnum.o								\
				$(OBJ_DIR_LIB)/my_str_isprintable.o							\
				$(OBJ_DIR_LIB)/my_str_isupper.o								\
				$(OBJ_DIR_LIB)/my_strlen.o									\
				$(OBJ_DIR_LIB)/my_strncat.o									\
				$(OBJ_DIR_LIB)/my_strncmp.o									\
				$(OBJ_DIR_LIB)/my_strncpy.o									\
				$(OBJ_DIR_LIB)/my_strstr.o									\
				$(OBJ_DIR_LIB)/my_str_to_int.o								\
				$(OBJ_DIR_LIB)/my_str_to_word_array.o						\
				$(OBJ_DIR_LIB)/my_strupcase.o								\
				$(OBJ_DIR_LIB)/my_swap.o									\
				$(OBJ_DIR_LIB)/my_putfloat.o								\
				$(OBJ_DIR_LIB)/my_putlong.o									\
				$(OBJ_DIR_LIB)/my_get_index_char.o							\
				$(OBJ_DIR_LIB)/my_count_char.o								\
				$(OBJ_DIR_LIB)/my_buffer.o									\
				$(OBJ_DIR_LIB)/remove_spaces.o								\
				$(OBJ_DIR_LIB)/my_binary_to_int.o							\
				$(OBJ_DIR_LIB)/concat_slash.o								\
				$(OBJ_DIR_LIB)/mem_set.o									\
				$(OBJ_DIR_LIB)/my_glue_cut_str.o							\
				$(OBJ_DIR_LIB)/gnl.o										\
				$(OBJ_DIR_LIB)/my_str_alpha_or_int.o						\
				$(OBJ_DIR_LIB)/my_char_is_alpha.o							\
				$(OBJ_DIR_LIB)/my_char_is_int.o								\
				$(OBJ_DIR_LIB)/my_print_address.o							\
				$(OBJ_DIR_LIB)/my_printf.o									\
				$(OBJ_DIR_LIB)/printfutils.o								\
				$(OBJ_DIR_LIB)/printfutils_two.o							\
				$(OBJ_DIR_LIB)/my_print_octal.o								\
				$(OBJ_DIR_LIB)/my_put_nbr_base.o							\
				$(OBJ_DIR_LIB)/add_zeros_to_char.o							\
				$(OBJ_DIR_LIB)/my_put_unsigned_int.o						\
				$(OBJ_DIR_LIB)/my_int_to_binary.o							\
				$(OBJ_DIR_LIB)/my_float_to_str.o							\
				$(OBJ_DIR_LIB)/concat.o										\
				$(OBJ_DIR_LIB)/my_str_to_float.o							\
				$(OBJ_DIR_LIB)/concat_with_char.o							\
				$(OBJ_DIR_LIB)/my_str_trim.o								\
				$(OBJ_DIR_LIB)/my_str_starts_with.o							\
				$(OBJ_DIR_LIB)/my_int_to_hexa.o


NAME_LIB =		libmy.a
NAME_HEADER =	$(SRC_DIR_LIB)/my.h



all: compil_lib copy_headers move_libmy

compil_lib:		$(OBJ_LIBRARY)
	@echo -e "${GREEN}[CREATE] ${WHITE}Creating ${BLUE}${NAME_LIB}${WHITE}...${NC}"
	@$(AR) rc $(NAME_LIB) $(OBJ_LIBRARY)

copy_headers:
	@echo -e "${GREEN}[COPY] ${WHITE}Copying ${BLUE}${NAME_HEADER}${WHITE} to ${BLUE}places${WHITE}...${NC}"
	@cp $(NAME_HEADER) ../../include


move_libmy:
	@mv $(NAME_LIB) ../..

debug:
	@gcc -g3 $(SRC_DIR_LIB)/*.c -l m

$(OBJ_DIR_LIB)%.o: $(SRC_DIR_LIB)%.c
	@mkdir -p obj
	@$(CC) -c $(CFLAGS) $< -o $@
	@echo -e "$(GREEN)[SUCCESS] ${BLUE}$@ ${NC}has finished compiling!"

clean:
	@echo -e "${GREEN}[CLEAN] ${WHITE}Removing ${BLUE}library objects${WHITE}...${NC}"
	@rm -rf $(OBJ_LIBRARY)

fclean: clean

re: fclean all

.PHONY: re